// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace UserAPI.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20260814065816_OtherCarOrder_carıd_added")]
    partial class OtherCarOrder_carıd_added
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsPassived")
                        .HasColumnType("bit");

                    b.Property<int?>("Kilometer")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PassivedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TankSize")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("User_id")
                        .HasColumnType("int");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("User_id");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("CarItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Car_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Item_amount")
                        .HasColumnType("int");

                    b.Property<string>("Item_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Item_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PassivedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("User_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Car_id");

                    b.HasIndex("User_id");

                    b.ToTable("CarItems");
                });

            modelBuilder.Entity("Debt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Debt_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Debtor_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsPayed")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsTaken")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PassivedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("User_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("User_id");

                    b.ToTable("Depts");
                });

            modelBuilder.Entity("FoodOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Food_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PassivedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Restaurant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("User_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("User_id");

                    b.ToTable("FoodOrders");
                });

            modelBuilder.Entity("FuelOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Car_id")
                        .HasColumnType("int");

                    b.Property<decimal?>("Fuel_liter")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OrderAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PassivedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Station")
                        .HasColumnType("int");

                    b.Property<decimal?>("Total_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Unit_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("User_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Car_id");

                    b.HasIndex("User_id");

                    b.ToTable("FuelOrders");
                });

            modelBuilder.Entity("OtherCarOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Car_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PassivedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("User_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Car_id");

                    b.HasIndex("User_id");

                    b.ToTable("OtherCarOrders");
                });

            modelBuilder.Entity("ParkingOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Car_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Free_hour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Hour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Hour_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Parking_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PassivedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Payment_type")
                        .HasColumnType("int");

                    b.Property<decimal?>("Total_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("User_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Car_id");

                    b.HasIndex("User_id");

                    b.ToTable("ParkingOrders");
                });

            modelBuilder.Entity("PassingOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Car_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PassivedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Payment_type")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("User_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Car_id");

                    b.HasIndex("User_id");

                    b.ToTable("PassingOrders");
                });

            modelBuilder.Entity("ThemeSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Notifications_enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Primary_color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Theme_mode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("User_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("User_id")
                        .IsUnique()
                        .HasFilter("[User_id] IS NOT NULL");

                    b.ToTable("ThemeSetting");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsPassived")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PassivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Car", b =>
                {
                    b.HasOne("User", "Owner")
                        .WithMany("Cars")
                        .HasForeignKey("User_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("CarItem", b =>
                {
                    b.HasOne("Car", "Car")
                        .WithMany("CarItems")
                        .HasForeignKey("Car_id");

                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("User_id");

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Debt", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany("Debts")
                        .HasForeignKey("User_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodOrder", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany("FoodOrders")
                        .HasForeignKey("User_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FuelOrder", b =>
                {
                    b.HasOne("Car", "Car")
                        .WithMany("FuelOrders")
                        .HasForeignKey("Car_id");

                    b.HasOne("User", "User")
                        .WithMany("FuelOrders")
                        .HasForeignKey("User_id");

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OtherCarOrder", b =>
                {
                    b.HasOne("Car", "Car")
                        .WithMany()
                        .HasForeignKey("Car_id");

                    b.HasOne("User", "User")
                        .WithMany("OtherCarOrders")
                        .HasForeignKey("User_id");

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ParkingOrder", b =>
                {
                    b.HasOne("Car", "Car")
                        .WithMany()
                        .HasForeignKey("Car_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany("ParkingOrders")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PassingOrder", b =>
                {
                    b.HasOne("Car", "Car")
                        .WithMany()
                        .HasForeignKey("Car_id");

                    b.HasOne("User", "User")
                        .WithMany("PassingOrders")
                        .HasForeignKey("User_id");

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThemeSetting", b =>
                {
                    b.HasOne("User", "User")
                        .WithOne("Settings")
                        .HasForeignKey("ThemeSetting", "User_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Car", b =>
                {
                    b.Navigation("CarItems");

                    b.Navigation("FuelOrders");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("Debts");

                    b.Navigation("FoodOrders");

                    b.Navigation("FuelOrders");

                    b.Navigation("OtherCarOrders");

                    b.Navigation("ParkingOrders");

                    b.Navigation("PassingOrders");

                    b.Navigation("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
